package main;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import lib.Login;
import lib.Querys;

/**
 *
 * @author Alexander Lopez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Importar variables de inicio de sesión
     */
    Login var = new Login();

    /**
     * Instancia de método de conexión
     */
    lib.Conexion con = new lib.Conexion();
    Connection cn = con.conexion();
    Statement st = con.conectar();
    Querys query = new Querys();

    /**
     * Constructor
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contabilidad = new javax.swing.JLabel();
        nomina = new javax.swing.JLabel();
        inventario = new javax.swing.JLabel();
        produccion = new javax.swing.JLabel();
        facturacion = new javax.swing.JLabel();
        gerencia = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        empresa = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        opciones = new javax.swing.JMenu();
        password = new javax.swing.JMenuItem();
        backup = new javax.swing.JMenuItem();
        parametros = new javax.swing.JMenuItem();
        admin = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        manual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contabilidad.png"))); // NOI18N
        contabilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contabilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contabilidadMouseClicked(evt);
            }
        });

        nomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nomina.png"))); // NOI18N
        nomina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nominaMouseClicked(evt);
            }
        });

        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario.png"))); // NOI18N
        inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventarioMouseClicked(evt);
            }
        });

        produccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producion.png"))); // NOI18N
        produccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        produccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produccionMouseClicked(evt);
            }
        });

        facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facturacion.png"))); // NOI18N
        facturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facturacionMouseClicked(evt);
            }
        });

        gerencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gerencial.png"))); // NOI18N
        gerencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gerencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerenciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contabilidad)
                        .addGap(34, 34, 34)
                        .addComponent(nomina))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(produccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(facturacion)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventario)
                    .addComponent(gerencia))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventario)
                    .addComponent(nomina)
                    .addComponent(contabilidad))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produccion)
                    .addComponent(facturacion)
                    .addComponent(gerencia))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        archivo.setText("Archivo");
        archivo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                archivoMenuSelected(evt);
            }
        });

        empresa.setText("Configurar Empresa");
        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });
        archivo.add(empresa);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        archivo.add(salir);

        menu.add(archivo);

        opciones.setText("Opciones");
        opciones.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                opcionesMenuSelected(evt);
            }
        });

        password.setText("Cambio Contraseña");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        opciones.add(password);

        backup.setText("Backup DB");
        backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupActionPerformed(evt);
            }
        });
        opciones.add(backup);

        parametros.setText("Parametros");
        parametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametrosActionPerformed(evt);
            }
        });
        opciones.add(parametros);

        admin.setText("Administrador");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        opciones.add(admin);

        menu.add(opciones);

        ayuda.setText("Ayuda");

        about.setText("Acerca de");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        ayuda.add(about);

        manual.setText("Manual");
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });
        ayuda.add(manual);

        menu.add(ayuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archivoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_archivoMenuSelected
        //Permisos
        if (Login.getPermiso() != 1) {
            empresa.setEnabled(false);
        }
    }//GEN-LAST:event_archivoMenuSelected

    private void opcionesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_opcionesMenuSelected
        //Permisos
        if (Login.getPermiso() != 1) {
            parametros.setEnabled(false);
            admin.setEnabled(false);
        } else {
            if (Login.getPermiso() == 2) {
                admin.setEnabled(false);
            }
        }
    }//GEN-LAST:event_opcionesMenuSelected

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        /**
         * Llamar parametros para configurar la empresa
         */
        new admon.Empresa().setVisible(true);
    }//GEN-LAST:event_empresaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        /**
         * Salir del programa
         */
        int salida = JOptionPane.showConfirmDialog(null, "¿Seguro desea salir?");
        if (JOptionPane.OK_OPTION == salida) {
            System.exit(0);
        }
    }//GEN-LAST:event_salirActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        /**
         * Llamada a cambio de contraseña
         */
        new admon.CambioPass().setVisible(true);
    }//GEN-LAST:event_passwordActionPerformed

    private void backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupActionPerformed
        /**
         * Crear backup de la base de datos
         */
        query.backup();
        try {
            boolean rs = st.execute(Querys.getBck());
            if (rs != true) {
                //System.out.print(query.bck);
                JOptionPane.showMessageDialog(null, "Copia de seguridad creada correctamente");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());
        }
    }//GEN-LAST:event_backupActionPerformed

    private void parametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametrosActionPerformed
        /**
         * LLamar la ventana de parametros
         */
        new admon.Parametros().setVisible(true);
    }//GEN-LAST:event_parametrosActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        /**
         * LLamar la ventana de administrador
         */
        new admon.Administrador().setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        /**
         * Llamar el about del programa
         */
        new acerca().setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        /**
         * Llamar el manual
         */
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\Backup\\110.pdf");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_manualActionPerformed

    private void contabilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contabilidadMouseClicked
        /**
         * Verificar permisos e inicar al modulo
         */
        if (Login.getPermiso() != 2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado", "Información", JOptionPane.CANCEL_OPTION);
        } else {
            new contabilidad.Contabilidad().setVisible(true);
        }
    }//GEN-LAST:event_contabilidadMouseClicked

    private void nominaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nominaMouseClicked
        /**
         * Verificar permisos e inicar al modulo
         */
        if (Login.getPermiso() != 3) {
            JOptionPane.showMessageDialog(null, "Acceso denegado", "Información", JOptionPane.CANCEL_OPTION);
        } else {
            new nomina.Inicio().setVisible(true);
        }
    }//GEN-LAST:event_nominaMouseClicked

    private void inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioMouseClicked
        /**
         * Verificar permisos e inicar al modulo
         */
        if (Login.getPermiso() != 4) {
            JOptionPane.showMessageDialog(null, "Acceso denegado", "Información", JOptionPane.CANCEL_OPTION);
        } else {
            new inventario.Inventario().setVisible(true);
        }
    }//GEN-LAST:event_inventarioMouseClicked

    private void produccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produccionMouseClicked
        /**
         * Verificar permisos e inicar al modulo
         */
        if (Login.getPermiso() != 5) {
            JOptionPane.showMessageDialog(null, "Acceso denegado", "Información", JOptionPane.CANCEL_OPTION);
        } else {
            new produccion.Produccion().setVisible(true);
        }
    }//GEN-LAST:event_produccionMouseClicked

    private void facturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturacionMouseClicked
         /**
         * Verificar permisos e inicar al modulo
         */
        if (Login.getPermiso() != 6) {
            JOptionPane.showMessageDialog(null, "Acceso denegado", "Información", JOptionPane.CANCEL_OPTION);
        } else {
            new facturacion.Pedido().setVisible(true);
        }
    }//GEN-LAST:event_facturacionMouseClicked

    private void gerenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciaMouseClicked
         /**
         * Verificar permisos e inicar al modulo
         */
        if (Login.getPermiso() != 7) {
            JOptionPane.showMessageDialog(null, "Acceso denegado", "Información", JOptionPane.CANCEL_OPTION);
        } else {
            new gerencia.Gerencia().setVisible(true);
        }
    }//GEN-LAST:event_gerenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             if ("Nimbus".equals(info.getName())) {
             javax.swing.UIManager.setLookAndFeel(info.getClassName());
             break;
             }
             }*/
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem admin;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuItem backup;
    private javax.swing.JLabel contabilidad;
    private javax.swing.JMenuItem empresa;
    private javax.swing.JLabel facturacion;
    private javax.swing.JLabel gerencia;
    private javax.swing.JLabel inventario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem manual;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel nomina;
    private javax.swing.JMenu opciones;
    private javax.swing.JMenuItem parametros;
    private javax.swing.JMenuItem password;
    private javax.swing.JLabel produccion;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
